### ISSUE TITLE
CRM Package Deployer Error

### ISSUE THREAD

**Issue by ciaomatteo** [devkeydet/dyn365-ce-devops#48]
Hey
Great work! But I'm getting an error in the "Primary Release - Dynamics Only" script:
`
2017-12-21T10:29:40.3009882Z ##[section]Starting: Deploy Dynamics 365 Package and Data using Package Deployer
2017-12-21T10:29:40.3013694Z ==============================================================================
2017-12-21T10:29:40.3013910Z Task         : MSCRM Package Deployer
2017-12-21T10:29:40.3014087Z Description  : Deploys a CRM Package using the CRM Package Deployer PowerShell Cmdlets
2017-12-21T10:29:40.3014250Z Version      : 9.0.8
2017-12-21T10:29:40.3014391Z Author       : Wael Hamze
2017-12-21T10:29:40.3014728Z Help         : For more information on CRM Package Deployer: https://technet.microsoft.com/en-us/library/dn647420.aspx
2017-12-21T10:29:40.3014926Z ==============================================================================
2017-12-21T10:29:58.0977513Z PackageDeployer Information: 8 : Starting Config Reading process:
2017-12-21T10:29:58.1120094Z PackageDeployer Information: 8 : ReadingConfig from : D:\A\R1\A\PRIMARY BUILD\DROP\DEPLOYMENTPACKAGE\BIN\RELEASE\PkgFolder\ImportConfig.xml
2017-12-21T10:29:58.1130735Z PackageDeployer Verbose: 16 : Unpacking config
2017-12-21T10:29:58.1848221Z PackageDeployer Information: 8 : Reading Solutions.. Please wait
2017-12-21T10:29:58.2945457Z PackageDeployer Verbose: 16 : Cleaning up Temp Working Directory - d:\a\_temp\gspbiv3u.b2p
2017-12-21T10:29:58.3185988Z PackageDeployer Information: 8 : Found One Custom Extension
2017-12-21T10:29:58.9084435Z PackageDeployer Information: 8 : Deployment Target Organization ID: 46c41d38-7e13-46d2-a0c1-6c7fae7654f6
2017-12-21T10:29:58.9092746Z PackageDeployer Information: 8 : Deployment Target Organization UniqueName: orgca8eb048
2017-12-21T10:29:58.9100943Z PackageDeployer Information: 8 : Deployment Target Organization Version: 9.0.0.3172
2017-12-21T10:29:58.9115281Z PackageDeployer Information: 8 : Deployment Target Organization Uri: https://avs100.api.crm4.dynamics.com/XRMServices/2011/Organization.svc
2017-12-21T10:29:58.9125277Z PackageDeployer Information: 8 : Deployment Target Organization Time marker: 12/21/2017 10:29:58 +00:00
2017-12-21T10:29:58.9168918Z PackageDeployer Information: 8 : Completed Config Reading process
2017-12-21T10:29:59.3656712Z PackageDeployer Information: 8 : Executing OverrideSolutionImportDecision Custom code
2017-12-21T10:29:59.3665581Z PackageDeployer Information: 8 : Processing Solution AsyncRequestResponseSample(AsyncRequestResponseSample) - Inbound version: 1.0.0.1 - Deployed Version 1.0.0.1, System Determined Import Action: SkipSameVersion
2017-12-21T10:30:46.8949035Z PackageDeployer Information: 8 : Executing read of DataImportBypass Custom code setting
2017-12-21T10:30:47.1102463Z PackageDeployer Information: 8 : Executing read of DataImportBypass Custom code setting
2017-12-21T10:30:47.1331017Z PackageDeployer Information: 8 : Reading OverrideDataImportSafetyChecks Custom Setting
2017-12-21T10:30:47.1883429Z PackageDeployer Information: 8 : Reading OverrideDateMode Custom Setting
2017-12-21T10:30:47.1884038Z PackageDeployer Information: 8 : Reading OverrideDataTimestamp Custom Setting
2017-12-21T10:30:52.4535656Z PackageDeployer Error: 2 : Message: Failed to execute Post Import Actions - Exception Raised
2017-12-21T10:30:52.4536479Z Source	: DeploymentPackage
2017-12-21T10:30:52.4536831Z Method	: AfterPrimaryImport
2017-12-21T10:30:52.4537205Z Date	: 10:30:52 AM
2017-12-21T10:30:52.4537530Z Time	: 12/21/2017
2017-12-21T10:30:52.4537941Z Error	: Method not found: 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageExtentionBase.ImportExtension.get_CrmSvc()'.
2017-12-21T10:30:52.4538347Z Stack Trace	: at PackageDeployer.PackageTemplate.AfterPrimaryImport()
2017-12-21T10:30:52.4538756Z    at Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore.ImportCode.BaseImportCustomizations.ExecutePostImportActions()
2017-12-21T10:30:52.4539151Z ======================================================================================================================
2017-12-21T10:30:52.4539427Z 
2017-12-21T10:30:52.4607405Z PackageDeployer Information: 8 : Executing read of DataImportBypass Custom code setting
2017-12-21T10:30:52.8800344Z ##[error]The pre-import process failed: Method not found: 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageExtentionBase.ImportExtension.get_CrmSvc()'.
2017-12-21T10:30:53.0209201Z Locating log file: d:\a\r1\a\Primary Build\drop\DeploymentPackage\bin\Release\Microsoft.Xrm.Tooling.PackageDeployment-2017-12-21.log
2017-12-21T10:30:53.0232338Z Writing Contents of Log File...
2017-12-21T10:30:53.0239270Z ------------------------------------------
2017-12-21T10:30:53.0286180Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Starting Config Reading process:
2017-12-21T10:30:53.0290803Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  ReadingConfig from : D:\A\R1\A\PRIMARY BUILD\DROP\DEPLOYMENTPACKAGE\BIN\RELEASE\PkgFolder\ImportConfig.xml
2017-12-21T10:30:53.0293310Z PackageDeployer	Verbose	16	12/21/2017 10:29:58 AM  Unpacking config
2017-12-21T10:30:53.0295844Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Reading Solutions.. Please wait
2017-12-21T10:30:53.0297745Z PackageDeployer	Verbose	16	12/21/2017 10:29:58 AM  Cleaning up Temp Working Directory - d:\a\_temp\gspbiv3u.b2p
2017-12-21T10:30:53.0300089Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Found One Custom Extension
2017-12-21T10:30:53.0302312Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Deployment Target Organization ID: 46c41d38-7e13-46d2-a0c1-6c7fae7654f6
2017-12-21T10:30:53.0304130Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Deployment Target Organization UniqueName: orgca8eb048
2017-12-21T10:30:53.0306507Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Deployment Target Organization Version: 9.0.0.3172
2017-12-21T10:30:53.0308629Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Deployment Target Organization Uri: https://avs100.api.crm4.dynamics.com/XRMServices/2011/Organization.svc
2017-12-21T10:30:53.0310759Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Deployment Target Organization Time marker: 12/21/2017 10:29:58 +00:00
2017-12-21T10:30:53.0312864Z PackageDeployer	Information	8	12/21/2017 10:29:58 AM  Completed Config Reading process
2017-12-21T10:30:53.0315094Z PackageDeployer	Information	8	12/21/2017 10:29:59 AM  Executing OverrideSolutionImportDecision Custom code
2017-12-21T10:30:53.0317005Z PackageDeployer	Information	8	12/21/2017 10:29:59 AM  Processing Solution AsyncRequestResponseSample(AsyncRequestResponseSample) - Inbound version: 1.0.0.1 - Deployed Version 1.0.0.1, System Determined Import Action: SkipSameVersion
2017-12-21T10:30:53.0319060Z PackageDeployer	Information	8	12/21/2017 10:30:46 AM  Executing read of DataImportBypass Custom code setting
2017-12-21T10:30:53.0321113Z PackageDeployer	Information	8	12/21/2017 10:30:47 AM  Executing read of DataImportBypass Custom code setting
2017-12-21T10:30:53.0322711Z PackageDeployer	Information	8	12/21/2017 10:30:47 AM  Reading OverrideDataImportSafetyChecks Custom Setting
2017-12-21T10:30:53.0324437Z PackageDeployer	Information	8	12/21/2017 10:30:47 AM  Reading OverrideDateMode Custom Setting
2017-12-21T10:30:53.0326719Z PackageDeployer	Information	8	12/21/2017 10:30:47 AM  Reading OverrideDataTimestamp Custom Setting
2017-12-21T10:30:53.0328997Z PackageDeployer	Error	2	12/21/2017 10:30:52 AM  Message: Failed to execute Post Import Actions - Exception Raised
2017-12-21T10:30:53.0331060Z Source	: DeploymentPackage
2017-12-21T10:30:53.0333082Z Method	: AfterPrimaryImport
2017-12-21T10:30:53.0334972Z Date	: 10:30:52 AM
2017-12-21T10:30:53.0337105Z Time	: 12/21/2017
2017-12-21T10:30:53.0339533Z Error	: Method not found: 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageExtentionBase.ImportExtension.get_CrmSvc()'.
2017-12-21T10:30:53.0341692Z Stack Trace	: at PackageDeployer.PackageTemplate.AfterPrimaryImport()
2017-12-21T10:30:53.0343822Z    at Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore.ImportCode.BaseImportCustomizations.ExecutePostImportActions()
2017-12-21T10:30:53.0348828Z ======================================================================================================================
2017-12-21T10:30:53.0350754Z 
2017-12-21T10:30:53.0353064Z PackageDeployer	Information	8	12/21/2017 10:30:52 AM  Executing read of DataImportBypass Custom code setting
2017-12-21T10:30:53.0362435Z ------------------------------------------
2017-12-21T10:30:53.1241674Z ##[section]Finishing: Deploy Dynamics 365 Package and Data using Package Deployer
`
Can you help me there?

**Comment by ciaomatteo** [comment]
Sorry, I was already on a dyn365 V9.0 version. So, I only had to update my nuget packages and everything worked perfectly fine.
Thanks!
